---
title: "THE IMPACT OF HEALTH FINANCING MODELS ON ACCESS TO CONVENTIONAL MEDICATION IN SIAYA COUNTY: EXAMINING IMPLICATIONS FOR EXPECTANT TEENAGE MOTHERS"
format: html
editor: visual
bibliography: references.bib
---

### Acronyms and Abbreviations

OOP - Out-of-Pocket Payment

NHI - National Health Insurance

SDG - Sustainable Development Goals

SHIF - Social Health Insurance Fund

UHC - Universal Health Coverage

## Introduction

### Background to the Study

UHC, as one of the Sustainable Development Goals (SDGs) is motivated by the need to make healthcare affordable to all based on need and not the ability to afford it @who2010world. Consequently, the available health financing models have direct implications on the ability of the poor and vulnerable to afford healthcare.

According to @ifeagwu2021health, OOP and NHI are among the top health financing mechanisms in sub-Saharan Africa. OOP, as a financing model, exposes the poor and vulnerable like teenagers to major challenges; the leading being the fact that teenagers are mostly not employed as they have not attained the age of majority, 18 years, which can allow them to legally and meaningfully get employed. @salari2019catastrophic established that the average OOP payment was Ksh 5613 for outpatient treatments, Ksh 1492 for inpatient treatments and Ksh 7990 for both types of treatment; all of these figures are way beyond the financial capability of most teenagers in Siaya County. Consequently, teenagers face challenges when it comes to relying on OOP as a health financing mechanism mainly because they don't have the money to spend on their healthcare.

The other major health financing model, NHI, is run by SHIF. Previously called NHIF, SHIF established the Linda Mama Scheme with the principal aim of ensuring universal access to free maternity services for expectant mothers throughout pregnancy and childbirth and thus catering to the poor and vulnerable @orangi2021examining. While @comfort2013effect noted that there is a positive correlation between health insurance and access to maternal health services, existing literature doesn't provide such evidence in the context of Siaya County. Also, @kamano2022awareness notes that in selected counties of Western Kenya, Siaya being one of them, there was a low NHIF uptake rate of between 21 - 25 %. The study also noted that one of the reasons for the low uptake was low level of education and low income status, which is a challenge that mainly affects teenagers since they are not meaningfully employable and besides have a low level of education.

In a bid to ensure universal access to maternal health services, the government introduced Linda Mama under the NHIF, which is a free health financing strategy exclusively targeting mothers and their newborns who cannot afford any cover including NHIF. However, Linda mama has faced various challenges as outlined by @orangi2021examining; key among them: the lack of knowledge about Linda mama among those seeking services and also healthcare service providers thus necessitating the need to improve communication of the program to health facilities using circulars and also to beneficiaries using regular health talks. @orangi2021examining also noted the need to monitor health facilities to ensure that the poor and vulnerable are not asked for any user fees when seeking Linda mama services.

### Statement of the Problem

@KDHS2022 survey, reported that 20.9% of the girls in Siaya County between the ages of 15 - 19 years old had begun child bearing. This proportion was way higher than most counties in the country and thus the need to ensure that teenagers in Siaya County are able to access conventional medication. @pd raised concerns by private healthcare providers on their unwillingness to continue offering services under Linda mama because of non-payment for services rendered since July 2023. These concerns threaten to throw the program into uncertainty thus threatening teenage mothers' ability to access conventional medication in Siaya County and the whole country at large.

While the literature review reveals that other studies have looked at the impact that health financing models have had on access conventional medication, special attention has not been given to Siaya County considering the fact that it bears a heavy burden when it comes to teenage pregnancy compared to other counties in the country.

Therefore, this study was conceived to look at the impact that major health financing models: OOP; NHIF and Linda mama have had on access to conventional medication in Siaya County, with a special focus on teenagers who are a major vulnerable group.

### Main Objective

The main objective was to investigate the influence of different health financing models on expectant teenage mothers' utilization of conventional medication in Siaya County.

### Research Objectives

1.  To investigate how OOP as a health financing model influence expectant teenage mothers' access to conventional medication in Siaya County.

2.  To investigate how NHIF(SHIF) as a health financing model influence expectant teenage mothers' access to conventional medication in Siaya County.

3.  To investigate how Linda Mama as a health financing model influence expectant teenage mothers' access to conventional medication in Siaya County.

### Research Questions

1.  How does OOP as a health financing model influence expectant teenage mothers' access to conventional medication in Siaya County?
2.  How does NHIF(SHIF) as a health financing model influence expectant teenage mothers' access to conventional medication in Siaya County?
3.  How does Linda mama as a health financing model influence expectant teenage mothers' access to conventional medication in Siaya County?

### Scope of the Study

This study will be carried out in the County of Siaya which comprises of six sub-counties: Alego, Usonga, Bondo, Ugenya, Ugunja, Gem and Rarieda.

### Limitations of the Study

hello

### Justification for the study.

Firstly, NHIF replacement with SHIF highlights the need for a rigorous re-evaluation of the same as a health financing model to determine the impact this move has had on access to conventional medication.

Secondly, the Linda mama program, a flagship policy initiative aimed at improving maternal health access and outcomes by providing free maternity services has faced implementation challenges as pointed out by @orangi2021examining. Besides, Linda mama, previously under NHIF, is now under SHIF; this too, highlights the need to re-evaluate the impact this shift has had on Linda mama as a health financing model and its implications when it comes to teenage mothers' access to conventional medication. Lastly, there have been a lot of concerns put across by healthcare providers on their ability to continue offering services under Linda mama considering that NHIF has failed to remit funds for services rendered since July 2023 thus throwing the program into uncertainty. @pd

This study therefore holds significant importance for various stakeholders in the healthcare sector because it will directly address the gap between policy formulation and implementation, providing insights that can inform future health financing policies. Besides, while existing literature acknowledges the challenges in maternal healthcare access, there is a lack of specific research focusing on the experiences of expectant teenage mothers particularly in light of a higher prevalence of teenage mothers in Siaya County as compared to other counties in Kenya: the @KDHS2022 survey reported that 20.9% of the girls between the ages of 15 - 19 years old in Siaya County had begun child bearing. This figure was way higher than most of the rest of the other counties in Kenya.

By focusing on teenage mothers, this study will fill an empirical gap in the literature. Moreover, the findings from this study will directly inform policy decisions aimed at improving maternal healthcare access and consequently outcomes in Kenya. By identifying the specific barriers faced by expectant teenage mothers and evaluating the effectiveness of different health financing models, the study will enable policymakers to design more targeted interventions to address these challenges and advance the goal of achieving universal health coverage.

### Definition of Terms

Teenager: Person aged between 13 - 19 years old.

### Organization of the Study

This study is organized into five chapters:

Chapter one (Introduction)

This chapter comprises of:

-   Background of the study

-   Justification for the study

-   Purpose of the study

-   Objectives

-   Research questions

-   Significance of the study

-   Scope of the study

-   Organization of the study

Chapter two (Literature Review)

This chapter comprises of:

-   Introduction

-   etc

## Literature Review.

### Introduction

Intro here...
